name: New Solar System Workflow 19

on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main
    #         - 'feature/*'
            
env:
    MONGO_URI: 'mongodb+srv://mongodb-prod.uizvbwm.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user # No a good practice for demo we are using it
          MONGO_PASSWORD: non-prod-password # No a good practice for demo we are using it
        strategy:
          matrix:
            os: [ubuntu-latest]
            node_js_version: [18, 20]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              #Ref: https://github.com/marketplace/actions/checkout

            - name: Setup NodeJS version - ${{ matrix.node_js_version }}
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node_js_version }}
              # Ref: https://github.com/marketplace/actions/setup-node-js-environment

            - name: Cache NPM Dependencies
              uses: actions/cache@v5
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

            - name: Intalling Dependencies
              run: npm install
            
            - name: Unit Testing
              id: nodejs_unit_testing_step
              run: npm test

            - name: Archive test result
              if: always()
              # if: failure() && (steps.nodejs_unit_testing_step.outcome == 'failure' || steps.nodejs_unit_testing_step.outcome == 'success')
              #Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#status-check-functions
              #Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#steps-context 
              uses: actions/upload-artifact@v7
              with:
                name: Mocha-Test-Result
                path: test-result.xml
              #Ref: https://github.com/marketplace/actions/upload-a-build-artifact
            
    code-coverage:
        name: Code Coverage
        # Defining Job Container:
        container:
          image: node:18
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options: 
                --name mongo #Container Name
        env:
          MONGO_URI: 'mongodb://mongo:27017/superData'
          MONGO_USERNAME: non-prod-user # No a good practice for demo we are using it
          MONGO_PASSWORD: non-prod-password # No a good practice for demo we are using it          
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
          #Ref: https://github.com/marketplace/actions/checkout

        # - name: Setup NodeJS version - 20
        #   uses: actions/setup-node@v6
        #   with:
        #     node-version: 20
        #   # Ref: https://github.com/marketplace/actions/setup-node-js-environment

        - name: Cache NPM Dependencies
          uses: actions/cache@v5
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}     
                 
        - name: Intalling Dependencies
          run: npm install
        
        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage  
          # 'continue-on-error: Can be defined at Job level or step leval'
          # Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepscontinue-on-error
          # Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idcontinue-on-error
          # If we will define at Step Level: Prevents a job from failing when a step fails. Set to true to allow a job to pass when this step fails.
          # If we will define at Job Level: Prevents a workflow run from failing when a job fails. Set to `true` to allow a workflow run to pass when this job fails.

        - name: Archive test result
          uses: actions/upload-artifact@v7
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5
          #Ref: https://github.com/marketplace/actions/upload-a-build-artifact

    docker:
        name: Containerization
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        permissions:
          packages: write
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: DockerHub Login
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Ref: https://github.com/marketplace/actions/docker-login

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v4
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
         # Ref(GITHUB_TOKEN): https://docs.github.com/en/actions/tutorials/authenticate-with-github_token 

        - name: Docker Build for Testing
          uses: docker/build-push-action@v7
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          # Ref: https://github.com/marketplace/actions/build-and-push-docker-images        

        - name: Docker Image Testing
          run: |
            docker images
            docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
        
            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP
        
            echo Testing Image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live

        - name: Set lowercase GitHub owner
          run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
          env:
              OWNER: ${{ github.repository_owner }} 
          # Added "Set lowercase GitHub owner" logic as previous workflow jobs failing due to username in upper case.

        - name: Pushing Image to Container-Registries
          uses: docker/build-push-action@v7
          with:
            context: .
            push: true
            tags: | 
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ env.OWNER_LC }}/solar-system:${{ github.sha }}

    dev-deploy:
        needs: docker
        environment: #Added Environment varibale logic it different to env.
          name: development
          url: https://${{ steps.set-host-ingress-add.outputs.APP_INGRESS_URL }}
        runs-on: ubuntu-latest
        outputs:
          APP_INGRESS_URL: ${{ steps.set-host-ingress-add.outputs.APP_INGRESS_URL }} #Ref to - Passing information between jobs
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              #Ref: https://github.com/marketplace/actions/checkout

            - name: Installing kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.34.0'
              #Ref: https://github.com/marketplace/actions/kubectl-tool-installer

            # As I don't have Ready Kubernetes cluster that's why commenting out thin section adding steps to provision miniKube cluster  
            # - name: Setting up Kubeconfig
            #   uses: azure/k8s-set-context@v5
            #   with:
            #       method: kubeconfig
            #       kubeconfig: ${{ secrets.KUBECONFIG}}
            #   # Ref: https://github.com/marketplace/actions/kubernetes-set-context
            
            - name: Setup minikube cluster
              id: minikube
              uses: medyagh/setup-minikube@latest
              with:
                addons: ingress
              # It's self explored action.
              # Ref: https://github.com/marketplace/actions/setup-minikube

            - name: Fetching Kubernetes Cluster Details
              run: |
                kubectl version
                echo -----------------------------------
                kubectl get nodes

            - name: Fetching ingress controller IP detils and store in GitHub actions Environment Variables
              run: |
                echo "INGRESS_IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> "$GITHUB_ENV"
              #Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-environment-variable

            - name: Replace placeholder tokens in menifests
              uses: cschleiden/replace-tokens@v1
              with:
                  tokenPrefix: '_{_'
                  tokenSuffix: '_}_'
                  files: '["kubernetes/development/*.yaml"]'
              env:
                  NAMESPACE: ${{ vars.NAMESPACE }}
                  REPLICAS: ${{ vars.REPLICAS }}
                  IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                  INGRESS_IP: ${{ env.INGRESS_IP }}
             #Ref: https://github.com/marketplace/actions/replace-tokens

            - name: Validating the manifests
              run: cat kubernetes/development/*.yaml

            - name: Creating a namespace
              run: kubectl create ns ${{ vars.NAMESPACE}}
              # Added this as I am tesing this on MiniKube

            - name: Create MongoDB Secret
              run: |
                kubectl -n ${{ vars.NAMESPACE}} create secret generic mongo-db-creds \
                --from-literals=MONGO_URI=${{ vars.MONGO_URI }} \
                --from-literals=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
                --from-literals=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -

            - name: Deploy to Dev Env
              run: kubectl apply -f kubernetes/development

            - name: Set App INGRESS host URL
              id: set-host-ingress-add
              run: |
                echo "APP_INGRESS_URL=$(kubectl -n ${{ vars.NAMESPACE}} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"
              # Passing information between jobs
              # Ref: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
              # Passing values between steps and jobs in a workflow
              # Ref: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-variables#passing-values-between-steps-and-jobs-in-a-workflow

    dev-integration-testing:
       name: Dev integration testing
       needs: dev-deploy
       runs-on: ubuntu-latest
       steps:
         - name: TEST URL output using CURL and JQ
           env:
             URL: ${{needs.dev-deploy.outputs.APP_INGRESS_URL}}
           #Ref to - Passing information between jobs
           run: |
             echo $URL
             echo "-------------------------------------"
             curl -s -k https://$URL/live | jq -r .status | grep -i live

    prod-deploy:
        needs: dev-integration-testing
        environment: #Added Environment varibale logic it different to env.
          name: production
          url: https://${{ steps.set-host-ingress-add.outputs.APP_INGRESS_URL }}
        runs-on: ubuntu-latest
        outputs:
          APP_INGRESS_URL: ${{ steps.set-host-ingress-add.outputs.APP_INGRESS_URL }} #Ref to - Passing information between jobs
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              #Ref: https://github.com/marketplace/actions/checkout

            - name: Installing kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.34.0'
              #Ref: https://github.com/marketplace/actions/kubectl-tool-installer

            # As I don't have Ready Kubernetes cluster that's why commenting out thin section adding steps to provision miniKube cluster  
            # - name: Setting up Kubeconfig
            #   uses: azure/k8s-set-context@v5
            #   with:
            #       method: kubeconfig
            #       kubeconfig: ${{ secrets.KUBECONFIG}}
            #   # Ref: https://github.com/marketplace/actions/kubernetes-set-context
            
            - name: Setup minikube cluster
              id: minikube
              uses: medyagh/setup-minikube@latest
              with:
                addons: ingress
              # It's self explored action.
              # Ref: https://github.com/marketplace/actions/setup-minikube

            - name: Fetching Kubernetes Cluster Details
              run: |
                kubectl version
                echo -----------------------------------
                kubectl get nodes

            - name: Fetching ingress controller IP detils and store in GitHub actions Environment Variables
              run: |
                echo "INGRESS_IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> "$GITHUB_ENV"
              #Ref: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-environment-variable

            - name: Replace placeholder tokens in menifests
              uses: cschleiden/replace-tokens@v1
              with:
                  tokenPrefix: '_{_'
                  tokenSuffix: '_}_'
                  files: '["kubernetes/production/*.yaml"]'
              env:
                  NAMESPACE: ${{ vars.NAMESPACE }}
                  REPLICAS: ${{ vars.REPLICAS }}
                  IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                  INGRESS_IP: ${{ env.INGRESS_IP }}
             #Ref: https://github.com/marketplace/actions/replace-tokens

            - name: Validating the manifests
              run: cat kubernetes/production/*.yaml

            - name: Creating a namespace
              run: kubectl create ns ${{ vars.NAMESPACE}}
              # Added this as I am tesing this on MiniKube

            - name: Create MongoDB Secret
              run: |
                kubectl -n ${{ vars.NAMESPACE}} create secret generic mongo-db-creds \
                --from-literals=MONGO_URI=${{ vars.MONGO_URI }} \
                --from-literals=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
                --from-literals=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -

            - name: Deploy to PROD Env
              run: kubectl apply -f kubernetes/production

            - name: Set App INGRESS host URL
              id: set-host-ingress-add
              run: |
                echo "APP_INGRESS_URL=$(kubectl -n ${{ vars.NAMESPACE}} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"
              # Passing information between jobs
              # Ref: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
              # Passing values between steps and jobs in a workflow
              # Ref: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-variables#passing-values-between-steps-and-jobs-in-a-workflow

    prod-integration-testing:
       name: PROD integration testing
       needs: prod-deploy
       runs-on: ubuntu-latest
       steps:
         - name: TEST URL output using CURL and JQ
           env:
             URL: ${{needs.prod-deploy.outputs.APP_INGRESS_URL}}
           #Ref to - Passing information between jobs
           run: |
             echo $URL
             echo "-------------------------------------"
             curl -s -k https://$URL/live | jq -r .status | grep -i live
    
    # Due to protection rule we applied using environment will restrict prod-deploy to because it is triggred from the feature branch.